### ISSUE TITLE
When i use extensions the consumer can not start up

### ISSUE THREAD

**Issue by zhaijp** [enadim/spring-cloud-ribbon-extensions#3]
My springcloud environment is
springcloud version ： Finchley.RELEASE

First I have add dependency like this
<dependency>
	<groupId>com.github.enadim</groupId>
	<artifactId>spring-cloud-ribbon-extensions</artifactId>
	<version>2.0.0</version>
</dependency>

Then create RibbonClientsConfig like this
@Configuration
@EnableRibbonStrictMetadataMatcher
public class RibbonClientsConfig {

}

Last create start up class like this

@RibbonClients(defaultConfiguration = RibbonClientsConfig.class)
@EnableDiscoveryClient
@SpringBootApplication
@EnableEurekaClient
@EnableContextPropagation
public class ConsumerApplication {
	
	@Bean
	@LoadBalanced
	RestTemplate restTemplate(){
		return new RestTemplate();
	}
	
	public static void main(String[] args) {
		SpringApplication.run(ConsumerApplication.class, args);
	}
}

After finish the three setps i start up the startup class but it can not startup and the logs is

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method strictMetadataMatcher in com.github.enadim.spring.cloud.ribbon.support.StrictMetadataMatcherConfig required a bean of type 'com.netflix.client.config.IClientConfig' that could not be found.

Action:

Consider defining a bean of type 'com.netflix.client.config.IClientConfig' in your configuration.

**Comment by zhaijp** [comment]
@enadim @ouaibsky

**Comment by enadim** [comment]
this is due to spring boot application that is loading the ribbon config as part of the main application context which is not how it should be. Ribbon loads for each client a specific spring context.
consider always defining the RibbonClientsConfig in a distinct package hierarchy than the spring application. 
for your use case example:
package myorg.consumer
class ConsumerApplication 

package myorg.ribbon
class RibbonClientsConfig

**Comment by zhaijp** [comment]
It works ,Thank you very much @enadim
